### ISSUE TITLE
Multiple fields on one plot

### ISSUE THREAD

**Issue by bnlawrence** [ajheaps/cf-view#7]
(and how to handle plotting when user selects multiple fields)

**Comment by ajheaps** [comment]
This was introduced at version 0.2.  The user selects the number of plots via the n-up drop-down and makes a plot by pressing the plot button.  When the required number of plots has been made then the image is displayed.  I'll mark this as closed but there are future improvements that could be considered such as:
A counter that shows down may plots are still left to be made before the plot is made.
The plot is displayed from the start and updated as the user makes each plot.
