### ISSUE TITLE
Plot box layout usability problems

### ISSUE THREAD

**Issue by bnlawrence** [ajheaps/cf-view#9]
Watching how Andy approached the plotbox in cfgui, it was obvious that the difference between configured plot and simple plot is confusing. Could we use a toggled button with configuraiton hidden if simple plot is shown? Needs revisiting.

**Comment by ajheaps** [comment]
I removed the plot configured button some time back as it was confusing.  The configuration options were relocated to the Configure option on the top bar in version 0.8.
